In [2]:
import numpy as np

# Numpy Indexing And Slicing Of Vectors

In [4]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[6]  # Indexing

17

In [6]:
arr[1:4]   # it exectutes till last-1 and if you leave starting value it defaults start from first position and for end value it defaults go till last position

array([12, 13, 14])

In [7]:
arr[2:]

array([13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[3::2]  #skips 2 values in between

array([14, 16, 18, 20])

# Numpy Indexing And Slicing Of Matrix

In [10]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[0] # indexing targets rows 0 prints 0 indexing rows

array([1, 2, 3, 4, 5])

In [12]:
arr[0,0] #for single element

1

In [13]:
arr[0:2,1:3] #slicing

array([[2, 3],
       [7, 8]])

In [14]:
arr[3:6,3:5] # or arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [15]:
arr[:,2] # for slicing columns

array([ 3,  8, 13, 18, 23, 28])

# Boolean Indexing

In [16]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [21]:
bool_index=arr%2==0
bool_index

array([ True,  True,  True,  True,  True])

In [22]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])