In [1]:
import numpy as np

# Basic Array Creation

In [2]:
arr=np.array([1,2,3,4]) #array
arr

array([1, 2, 3, 4])

In [4]:
a=[1,2,3.5,4]  #list
a

[1, 2, 3.5, 4]

In [5]:
np.array(a) # if we pass float with int it will convert everything to float and if we pass string it converts to string

array([1. , 2. , 3.5, 4. ])

In [6]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Generation Function

In [10]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [14]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [18]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
arr=np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [22]:
arr=np.linspace(1,5,3)  # np.linspace(start, stop, num): Generates 'num' evenly spaced numbers in a range
arr

array([1., 3., 5.])

# Random Generation Function

In [23]:
np.random.rand(5) #creates random 5 elements and all value are in 0 and 1 range

array([0.94955597, 0.03293545, 0.01079573, 0.37470799, 0.46118772])

In [24]:
np.random.randn(10) # values are in range -3 to 3

array([-0.94087496, -0.25010153,  1.63606056, -0.44557503,  0.14269225,
       -0.36520027,  0.0481805 , -0.32699546,  1.2697486 ,  2.55496805])

In [25]:
np.random.randint(6) #it will give any random int between 0 to 6

1

In [26]:
np.random.randint(10,20,10)

array([17, 11, 11, 13, 10, 10, 12, 13, 12, 10])

# Array Attributes

In [27]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr.shape # write attributes without bracket always

(3, 3)

In [29]:
arr.size

9

In [30]:
arr.dtype

dtype('int32')

# Array Methods

In [31]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr.min()

1

In [33]:
arr.max()

9

In [34]:
arr.sum()

45

In [36]:
np.sum(arr,axis=0) # if you want column wise sum write axis=0 and for row wise write axis=1

array([12, 15, 18])

In [37]:
arr.mean()

5.0

In [38]:
arr.std()

2.581988897471611

In [39]:
arr.argmax() # Index of max element

8

In [40]:
arr.argmin()

0

# Reshaping and Resizing

In [41]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [44]:
arr=arr.reshape(6,5)  #6*5=30 and we have 30 elements in arr

In [45]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])