In [1]:
import numpy as np

# Arithmetic Operations

In [3]:
a1=np.array([1,2,3,4,5])   # Size must be same of both arrays
a2=np.array([6,7,8,9,10])

In [5]:
arr2=a1+a2
arr2

array([ 7,  9, 11, 13, 15])

In [6]:
a1 -a2

array([-5, -5, -5, -5, -5])

In [7]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

# Broadcasting

In [9]:
l=[19,29,30,40]
arr=np.array(l)

In [10]:
l+10

TypeError: can only concatenate list (not "int") to list

In [11]:
arr+10 # all elements get impacted

array([29, 39, 40, 50])

# Deep and Shallow copy

In [13]:
a=np.arange(1,21)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
slice= a[:5] #shallow copy and when array get changed it is deep copy
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [16]:
a # when you perform any operation in slicing it will not be updated in you main arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
a[4:6]*10

array([50, 60])

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
a   #deep copy for shallow copy
b=a  #write a.copy()

In [20]:
b[0]=99

In [21]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Matrix Multiplication

In [23]:
A=np.array([[1,2],[3,4]])
B=np.array([[6,7],[8,9]])

In [24]:
A*B   # but now how this is matrix mul works

array([[ 6, 14],
       [24, 36]])

In [25]:
A @ B

array([[22, 25],
       [50, 57]])

In [26]:
A.T

array([[1, 3],
       [2, 4]])

# Advance Array Multiplication

In [27]:
A=np.array([1,2,3,4]) #you cannot stack matrix
B=np.array([6,7,8,9])

In [29]:
np.vstack((A,B))  #vertically stacked

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [30]:
np.hstack((A,B))

array([1, 2, 3, 4, 6, 7, 8, 9])

In [31]:
np.column_stack((A,B))

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

# Splitting Array

In [32]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
np.hsplit(c,2) # you need equal division

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [34]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]